kind: ServiceAccount
apiVersion: v1
metadata:
  name: github-actions
  namespace: ${LICENSE_PLATE}-${ENVIRONMENT}

parameters:
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: License Plate
    displayName: License Plate
    name: LICENSE_PLATE
    required: true
    value: b996e6
